version: "3"
services:
 kademlia_bootstrap:
    image: kademlia:latest
    stdin_open: true
    tty: true
    hostname: kademlia_bootstrap_host
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
 kademlia_nodes:
    image: kademlia:latest
    stdin_open: true
    tty: true
    links: 
      - kademlia_bootstrap:kademlia_bootstrap_host
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  kademlia_network: