// Code generated by protoc-gen-go. DO NOT EDIT.
// source: networkmessage.proto

package kademlia

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	KademliaId           string   `protobuf:"bytes,2,opt,name=kademlia_id,json=kademliaId,proto3" json:"kademlia_id,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Ping) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *Ping) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ping) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Pong struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	KademliaId           string   `protobuf:"bytes,2,opt,name=kademlia_id,json=kademliaId,proto3" json:"kademlia_id,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Pong) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *Pong) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Pong) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Find struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Find) Reset()         { *m = Find{} }
func (m *Find) String() string { return proto.CompactTextString(m) }
func (*Find) ProtoMessage()    {}
func (*Find) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{2}
}

func (m *Find) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Find.Unmarshal(m, b)
}
func (m *Find) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Find.Marshal(b, m, deterministic)
}
func (m *Find) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Find.Merge(m, src)
}
func (m *Find) XXX_Size() int {
	return xxx_messageInfo_Find.Size(m)
}
func (m *Find) XXX_DiscardUnknown() {
	xxx_messageInfo_Find.DiscardUnknown(m)
}

var xxx_messageInfo_Find proto.InternalMessageInfo

func (m *Find) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Find) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Store struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	KademliaId           string   `protobuf:"bytes,2,opt,name=kademlia_id,json=kademliaId,proto3" json:"kademlia_id,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Content              []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Pin                  bool     `protobuf:"varint,5,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{3}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *Store) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *Store) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Store) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Store) GetPin() bool {
	if m != nil {
		return m.Pin
	}
	return false
}

type StoreResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	KademliaId           string   `protobuf:"bytes,2,opt,name=kademlia_id,json=kademliaId,proto3" json:"kademlia_id,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{4}
}

func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (m *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(m, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

func (m *StoreResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StoreResponse) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *StoreResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Node struct {
	KademliaId           string   `protobuf:"bytes,1,opt,name=kademlia_id,json=kademliaId,proto3" json:"kademlia_id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetKademliaId() string {
	if m != nil {
		return m.KademliaId
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type NodeResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeResponse) Reset()         { *m = NodeResponse{} }
func (m *NodeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeResponse) ProtoMessage()    {}
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{6}
}

func (m *NodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeResponse.Unmarshal(m, b)
}
func (m *NodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeResponse.Marshal(b, m, deterministic)
}
func (m *NodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResponse.Merge(m, src)
}
func (m *NodeResponse) XXX_Size() int {
	return xxx_messageInfo_NodeResponse.Size(m)
}
func (m *NodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResponse proto.InternalMessageInfo

func (m *NodeResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *NodeResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ValueResponse struct {
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Response:
	//	*ValueResponse_Nodes
	//	*ValueResponse_Content
	Response             isValueResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ValueResponse) Reset()         { *m = ValueResponse{} }
func (m *ValueResponse) String() string { return proto.CompactTextString(m) }
func (*ValueResponse) ProtoMessage()    {}
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{7}
}

func (m *ValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueResponse.Unmarshal(m, b)
}
func (m *ValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueResponse.Marshal(b, m, deterministic)
}
func (m *ValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueResponse.Merge(m, src)
}
func (m *ValueResponse) XXX_Size() int {
	return xxx_messageInfo_ValueResponse.Size(m)
}
func (m *ValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValueResponse proto.InternalMessageInfo

func (m *ValueResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type isValueResponse_Response interface {
	isValueResponse_Response()
}

type ValueResponse_Nodes struct {
	Nodes *NodeResponse `protobuf:"bytes,2,opt,name=nodes,proto3,oneof"`
}

type ValueResponse_Content struct {
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3,oneof"`
}

func (*ValueResponse_Nodes) isValueResponse_Response() {}

func (*ValueResponse_Content) isValueResponse_Response() {}

func (m *ValueResponse) GetResponse() isValueResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ValueResponse) GetNodes() *NodeResponse {
	if x, ok := m.GetResponse().(*ValueResponse_Nodes); ok {
		return x.Nodes
	}
	return nil
}

func (m *ValueResponse) GetContent() []byte {
	if x, ok := m.GetResponse().(*ValueResponse_Content); ok {
		return x.Content
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ValueResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ValueResponse_Nodes)(nil),
		(*ValueResponse_Content)(nil),
	}
}

type Packet struct {
	Ping                 *Ping          `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	Pong                 *Pong          `protobuf:"bytes,2,opt,name=pong,proto3" json:"pong,omitempty"`
	Store                *Store         `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	StoreResponse        *StoreResponse `protobuf:"bytes,4,opt,name=StoreResponse,proto3" json:"StoreResponse,omitempty"`
	FindNode             *Find          `protobuf:"bytes,5,opt,name=find_node,json=findNode,proto3" json:"find_node,omitempty"`
	Nodes                *ValueResponse `protobuf:"bytes,6,opt,name=nodes,proto3" json:"nodes,omitempty"`
	FindValue            *Find          `protobuf:"bytes,7,opt,name=find_value,json=findValue,proto3" json:"find_value,omitempty"`
	Value                *ValueResponse `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	Origin               *Node          `protobuf:"bytes,9,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee87f1373a8d2499, []int{8}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *Packet) GetPong() *Pong {
	if m != nil {
		return m.Pong
	}
	return nil
}

func (m *Packet) GetStore() *Store {
	if m != nil {
		return m.Store
	}
	return nil
}

func (m *Packet) GetStoreResponse() *StoreResponse {
	if m != nil {
		return m.StoreResponse
	}
	return nil
}

func (m *Packet) GetFindNode() *Find {
	if m != nil {
		return m.FindNode
	}
	return nil
}

func (m *Packet) GetNodes() *ValueResponse {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Packet) GetFindValue() *Find {
	if m != nil {
		return m.FindValue
	}
	return nil
}

func (m *Packet) GetValue() *ValueResponse {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Packet) GetOrigin() *Node {
	if m != nil {
		return m.Origin
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "Ping")
	proto.RegisterType((*Pong)(nil), "Pong")
	proto.RegisterType((*Find)(nil), "Find")
	proto.RegisterType((*Store)(nil), "Store")
	proto.RegisterType((*StoreResponse)(nil), "StoreResponse")
	proto.RegisterType((*Node)(nil), "Node")
	proto.RegisterType((*NodeResponse)(nil), "NodeResponse")
	proto.RegisterType((*ValueResponse)(nil), "ValueResponse")
	proto.RegisterType((*Packet)(nil), "Packet")
}

func init() { proto.RegisterFile("networkmessage.proto", fileDescriptor_ee87f1373a8d2499) }

var fileDescriptor_ee87f1373a8d2499 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4f, 0x6f, 0xd4, 0x30,
	0x10, 0xc5, 0x9b, 0xcd, 0x9f, 0x66, 0x27, 0xbb, 0x08, 0x59, 0x1c, 0xc2, 0x9f, 0x8a, 0x2a, 0x2a,
	0x52, 0x4e, 0x39, 0x04, 0x2e, 0x5c, 0x7b, 0x40, 0x2d, 0x07, 0x54, 0x19, 0xc1, 0x81, 0x4b, 0x15,
	0x6a, 0x93, 0x5a, 0xdb, 0xda, 0xc1, 0x76, 0xe1, 0xc4, 0x99, 0x8f, 0xc6, 0xd7, 0x42, 0x33, 0x71,
	0xd8, 0xed, 0xaa, 0x82, 0x95, 0x10, 0xdc, 0x9c, 0x37, 0xf5, 0xef, 0x8d, 0xe7, 0x4d, 0x17, 0x1e,
	0x68, 0xe9, 0xbf, 0x1a, 0xbb, 0xba, 0x96, 0xce, 0x75, 0xbd, 0x6c, 0x06, 0x6b, 0xbc, 0xa9, 0x3c,
	0x24, 0x67, 0x4a, 0xf7, 0xec, 0x00, 0xc0, 0xca, 0xcf, 0x37, 0xd2, 0xf9, 0x73, 0x25, 0xca, 0xe8,
	0x30, 0xaa, 0xe7, 0x7c, 0x1e, 0x94, 0x53, 0xc1, 0x9e, 0x42, 0xb1, 0xea, 0x84, 0xbc, 0xbe, 0x52,
	0x1d, 0xd6, 0x67, 0x54, 0x87, 0x49, 0x3a, 0x15, 0xac, 0x84, 0xfd, 0x4e, 0x08, 0x2b, 0x9d, 0x2b,
	0x63, 0x2a, 0x4e, 0x9f, 0x8c, 0x41, 0x32, 0x18, 0xeb, 0xcb, 0x84, 0x64, 0x3a, 0x93, 0xab, 0xf9,
	0xef, 0xae, 0x2f, 0x21, 0x79, 0xa5, 0xb4, 0xf8, 0x93, 0x2b, 0x83, 0xe4, 0xb2, 0x73, 0x97, 0xc1,
	0x8e, 0xce, 0xd5, 0xf7, 0x08, 0xd2, 0xb7, 0xde, 0x58, 0xf9, 0xd7, 0x2d, 0x4f, 0xf4, 0x78, 0x4d,
	0xc7, 0x67, 0x5c, 0x18, 0xed, 0xa5, 0x1e, 0xfb, 0x5d, 0xf0, 0xe9, 0x93, 0xdd, 0x87, 0x78, 0x50,
	0xba, 0x4c, 0x0f, 0xa3, 0x3a, 0xe7, 0x78, 0xac, 0x14, 0x2c, 0xa9, 0x11, 0x2e, 0xdd, 0x60, 0xb4,
	0x93, 0xff, 0x6e, 0x86, 0xd5, 0x3b, 0x48, 0xde, 0x18, 0x21, 0xb7, 0x11, 0xd1, 0xef, 0x10, 0xb3,
	0xbb, 0x63, 0x88, 0x37, 0x62, 0x78, 0x0d, 0x0b, 0xc4, 0xee, 0xfa, 0x80, 0xc7, 0x90, 0x6a, 0x23,
	0x24, 0xa2, 0xe3, 0xba, 0x68, 0xd3, 0x86, 0x2e, 0x8f, 0x5a, 0xf5, 0x0d, 0x96, 0xef, 0xbb, 0xab,
	0x9b, 0x9d, 0x61, 0xcf, 0xd6, 0xb0, 0xa8, 0x2e, 0xda, 0x65, 0xb3, 0xd9, 0xc9, 0xc9, 0x5e, 0xc0,
	0xb2, 0x47, 0xeb, 0x40, 0xb0, 0xf3, 0xc5, 0xc9, 0xde, 0xaf, 0x48, 0x8e, 0x01, 0x72, 0x1b, 0x2e,
	0x54, 0x3f, 0x66, 0x90, 0x9d, 0x75, 0x17, 0x2b, 0xe9, 0xd9, 0x43, 0x48, 0x06, 0xa5, 0x7b, 0xb2,
	0xc4, 0x2e, 0xf1, 0xbf, 0x8a, 0x93, 0x44, 0x25, 0xa3, 0xfb, 0xe0, 0x99, 0x36, 0xb8, 0xfa, 0x9c,
	0x24, 0xf6, 0x04, 0x52, 0x87, 0x69, 0x92, 0x4d, 0xd1, 0x66, 0xcd, 0x98, 0xed, 0x28, 0xb2, 0x17,
	0x5b, 0x59, 0xd3, 0x76, 0x14, 0xed, 0xbd, 0xe6, 0x96, 0xca, 0xb7, 0x16, 0xa2, 0x82, 0xf9, 0x27,
	0xa5, 0xc5, 0x39, 0x3e, 0x85, 0x36, 0x07, 0x3d, 0x71, 0xf1, 0x79, 0x8e, 0x3a, 0x45, 0x7a, 0x34,
	0xcd, 0x21, 0x0b, 0xc4, 0x5b, 0x53, 0x9c, 0xc6, 0x70, 0x04, 0x40, 0xa4, 0x2f, 0x58, 0x2c, 0xf7,
	0x37, 0x51, 0x64, 0x41, 0x97, 0x90, 0x35, 0xfe, 0x41, 0x7e, 0x37, 0x8b, 0x8a, 0xec, 0x00, 0x32,
	0x63, 0x55, 0xaf, 0x74, 0x39, 0x0f, 0x1c, 0x1a, 0x7d, 0x10, 0x8f, 0xe1, 0x43, 0x3e, 0x2d, 0xd4,
	0xc7, 0x8c, 0x7e, 0x9a, 0x9e, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x1a, 0xdc, 0xd6, 0xb2,
	0x04, 0x00, 0x00,
}
